# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - '.git/**/*'
    - '.vscode/**/*'
    - '.yarn/**/*'
    - 'config/routes.rb'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'sql/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
